# Builds static content for GitHub pages.

name: Build website

on:
  push:
    branches:
      # 'legacy-docs-main' triggers updates to 'legacy.sleap.ai'
      - legacy-docs-main
  workflow_dispatch:  # Allows manual triggering from GitHub UI


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      # Setup
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3.0.3
        with:
          python-version: 3.7
          environment-file: environment_website_build.yml
          activate-environment: sleap_ci
      - name: Print environment info
        shell: bash -l {0}
        run: |
          which python
          conda info

      - name: Build
        shell: bash -l {0}
        run: |
          cd docs
          python make_api_doctree.py
          make html

      - name: Deploy (legacy.sleap.ai)
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/legacy-docs-main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: docs/build/html
          keep_files: true